/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Car {
  'id' : string,
  'model' : string,
  'imageUrls' : Array<string>,
  'owner' : Principal,
  'make' : string,
  'color' : string,
  'year' : string,
  'description' : string,
  'modifications' : Array<string>,
}
export interface ClubView {
  'id' : string,
  'coverImageUrl' : string,
  'creator' : Principal,
  'members' : Array<Principal>,
  'name' : string,
  'description' : string,
  'category' : string,
}
export interface Comment {
  'id' : string,
  'content' : string,
  'author' : Principal,
  'timestamp' : bigint,
  'postId' : string,
}
export interface EventView {
  'id' : string,
  'coverImageUrl' : string,
  'title' : string,
  'creator' : Principal,
  'maxAttendees' : bigint,
  'description' : string,
  'attendees' : Array<Principal>,
  'category' : string,
  'location' : string,
  'eventDate' : bigint,
}
export interface Listing {
  'id' : string,
  'title' : string,
  'imageUrls' : Array<string>,
  'description' : string,
  'isSold' : boolean,
  'seller' : Principal,
  'category' : string,
  'price' : bigint,
  'location' : string,
  'condition' : string,
}
export interface Message {
  'id' : string,
  'content' : string,
  'sender' : Principal,
  'timestamp' : bigint,
  'receiver' : Principal,
}
export interface Notification {
  'id' : string,
  'notifType' : string,
  'user' : Principal,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
  'relatedId' : string,
}
export interface PostView {
  'id' : string,
  'postType' : string,
  'content' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : bigint,
  'mediaUrls' : Array<string>,
  'comments' : Array<string>,
}
export interface Profile {
  'bio' : string,
  'displayName' : string,
  'avatarUrl' : string,
  'bannerUrl' : string,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCar' : ActorMethod<
    [string, string, string, string, string, Array<string>, Array<string>],
    string
  >,
  'addComment' : ActorMethod<[string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClub' : ActorMethod<[string, string, string, string], string>,
  'createEvent' : ActorMethod<
    [string, string, string, bigint, string, string, bigint],
    string
  >,
  'createListing' : ActorMethod<
    [string, string, bigint, string, string, Array<string>, string],
    string
  >,
  'createNotification' : ActorMethod<[string, string, string], string>,
  'createPost' : ActorMethod<[string, Array<string>, string], string>,
  'deleteListing' : ActorMethod<[string], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAllPosts' : ActorMethod<[], Array<PostView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClubMembers' : ActorMethod<[string], Array<Principal>>,
  'getCommentsForPost' : ActorMethod<[string], Array<Comment>>,
  'getConversations' : ActorMethod<[], Array<Principal>>,
  'getEventAttendees' : ActorMethod<[string], Array<Principal>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getGarageByUser' : ActorMethod<[Principal], Array<Car>>,
  'getMessagesWithUser' : ActorMethod<[Principal], Array<Message>>,
  'getMyGarage' : ActorMethod<[], Array<Car>>,
  'getMyProfile' : ActorMethod<[], [] | [Profile]>,
  'getPostsByUser' : ActorMethod<[Principal], Array<PostView>>,
  'getProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'joinClub' : ActorMethod<[string], undefined>,
  'leaveClub' : ActorMethod<[string], undefined>,
  'likePost' : ActorMethod<[string], undefined>,
  'listAllClubs' : ActorMethod<[], Array<ClubView>>,
  'listAllEvents' : ActorMethod<[], Array<EventView>>,
  'listAllListings' : ActorMethod<[], Array<Listing>>,
  'listMyNotifications' : ActorMethod<[], Array<Notification>>,
  'markListingSold' : ActorMethod<[string], undefined>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'removeCar' : ActorMethod<[string], undefined>,
  'rsvpEvent' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], string>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikePost' : ActorMethod<[string], undefined>,
  'unrsvpEvent' : ActorMethod<[string], undefined>,
  'updateProfile' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];