/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostView = IDL.Record({
  'id' : IDL.Text,
  'postType' : IDL.Text,
  'topic' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'likes' : IDL.Vec(IDL.Principal),
  'timestamp' : IDL.Int,
  'mediaUrls' : IDL.Vec(IDL.Text),
  'comments' : IDL.Vec(IDL.Text),
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'bannerUrl' : IDL.Text,
  'location' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Int,
  'postId' : IDL.Text,
});
export const Car = IDL.Record({
  'id' : IDL.Text,
  'model' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'owner' : IDL.Principal,
  'make' : IDL.Text,
  'color' : IDL.Text,
  'year' : IDL.Text,
  'description' : IDL.Text,
  'modifications' : IDL.Vec(IDL.Text),
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : IDL.Int,
  'receiver' : IDL.Principal,
});
export const ClubView = IDL.Record({
  'id' : IDL.Text,
  'coverImageUrl' : IDL.Text,
  'creator' : IDL.Principal,
  'members' : IDL.Vec(IDL.Principal),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const EventView = IDL.Record({
  'id' : IDL.Text,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'maxAttendees' : IDL.Nat,
  'description' : IDL.Text,
  'attendees' : IDL.Vec(IDL.Principal),
  'category' : IDL.Text,
  'location' : IDL.Text,
  'eventDate' : IDL.Int,
  'photos' : IDL.Vec(IDL.Text),
});
export const Listing = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'isSold' : IDL.Bool,
  'seller' : IDL.Principal,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'location' : IDL.Text,
  'condition' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'notifType' : IDL.Text,
  'user' : IDL.Principal,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'relatedId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCar' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'addComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'addEventPhoto' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClub' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'createNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deleteListing' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClubMembers' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Principal)], ['query']),
  'getCommentsForPost' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getEventAttendees' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getEventPhotos' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getGarageByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Car)], ['query']),
  'getMessagesWithUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyGarage' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(PostView)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'joinClub' : IDL.Func([IDL.Text], [], []),
  'leaveClub' : IDL.Func([IDL.Text], [], []),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'listAllClubs' : IDL.Func([], [IDL.Vec(ClubView)], ['query']),
  'listAllEvents' : IDL.Func([], [IDL.Vec(EventView)], ['query']),
  'listAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
  'listMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'markListingSold' : IDL.Func([IDL.Text], [], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'removeCar' : IDL.Func([IDL.Text], [], []),
  'rsvpEvent' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
  'sendNotificationToUser' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  'unlikePost' : IDL.Func([IDL.Text], [], []),
  'unrsvpEvent' : IDL.Func([IDL.Text], [], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostView = IDL.Record({
    'id' : IDL.Text,
    'postType' : IDL.Text,
    'topic' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'likes' : IDL.Vec(IDL.Principal),
    'timestamp' : IDL.Int,
    'mediaUrls' : IDL.Vec(IDL.Text),
    'comments' : IDL.Vec(IDL.Text),
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'bannerUrl' : IDL.Text,
    'location' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
    'postId' : IDL.Text,
  });
  const Car = IDL.Record({
    'id' : IDL.Text,
    'model' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'owner' : IDL.Principal,
    'make' : IDL.Text,
    'color' : IDL.Text,
    'year' : IDL.Text,
    'description' : IDL.Text,
    'modifications' : IDL.Vec(IDL.Text),
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : IDL.Int,
    'receiver' : IDL.Principal,
  });
  const ClubView = IDL.Record({
    'id' : IDL.Text,
    'coverImageUrl' : IDL.Text,
    'creator' : IDL.Principal,
    'members' : IDL.Vec(IDL.Principal),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const EventView = IDL.Record({
    'id' : IDL.Text,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'maxAttendees' : IDL.Nat,
    'description' : IDL.Text,
    'attendees' : IDL.Vec(IDL.Principal),
    'category' : IDL.Text,
    'location' : IDL.Text,
    'eventDate' : IDL.Int,
    'photos' : IDL.Vec(IDL.Text),
  });
  const Listing = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'isSold' : IDL.Bool,
    'seller' : IDL.Principal,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'location' : IDL.Text,
    'condition' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'notifType' : IDL.Text,
    'user' : IDL.Principal,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'relatedId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCar' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'addComment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'addEventPhoto' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClub' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'createNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deleteListing' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClubMembers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getCommentsForPost' : IDL.Func([IDL.Text], [IDL.Vec(Comment)], ['query']),
    'getConversations' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getEventAttendees' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getEventPhotos' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getGarageByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Car)], ['query']),
    'getMessagesWithUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyGarage' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getPostsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PostView)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'joinClub' : IDL.Func([IDL.Text], [], []),
    'leaveClub' : IDL.Func([IDL.Text], [], []),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'listAllClubs' : IDL.Func([], [IDL.Vec(ClubView)], ['query']),
    'listAllEvents' : IDL.Func([], [IDL.Vec(EventView)], ['query']),
    'listAllListings' : IDL.Func([], [IDL.Vec(Listing)], ['query']),
    'listMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'markListingSold' : IDL.Func([IDL.Text], [], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'removeCar' : IDL.Func([IDL.Text], [], []),
    'rsvpEvent' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Text], []),
    'sendNotificationToUser' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
    'unlikePost' : IDL.Func([IDL.Text], [], []),
    'unrsvpEvent' : IDL.Func([IDL.Text], [], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };